FROM ubuntu:14.04
RUN apt-get update -y \ 
    && apt-get install -y python-setuptools python-pip
ADD requirements.txt /src/requirements.txt
RUN cd /src; pip install -r requirements.txt
ADD . /src
EXPOSE 5000
ENV  PASSWORD $CLOUDARK_CLOUDSQL_Password
ENV  DB $CLOUDARK_CLOUDSQL_DBName
ENV  HOST $CLOUDARK_CLOUDSQL_Address
ENV  USER $CLOUDARK_CLOUDSQL_Username
CMD ["python", "/src/application.py"]
